### PR TITLE
Changed spectroscopy notebook

### PR DESCRIPTION
**Pull request by ch-stefanhi**

### CODE REVIEW

**Comment by wikfeldt** [comment]
@ch-stefanhi the automatic deployment of this fails with the following error:

```
Exception occurred:
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbformat/reader.py", line 26, in parse_json
    raise NotJSONError(message) from e
nbformat.reader.NotJSONError: Notebook does not appear to be JSON: '{\n "cells": [\n  {\n   "cell_type": "m...
The full traceback has been saved in /tmp/sphinx-err-bvsazt39.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:20: dirhtml] Error 2
Error: Process completed with exit code 2.
```

does that make sense to you? do you know how the notebook can be fixed to solve this?

**Comment by ch-stefanhi** [comment]
No clue atm, but I can send you the notebook via email as soon as I'm home (approx 21:00)
________________________________

**Comment by wikfeldt** [comment]
there seems to be some error with the json itself. A JSON validator (https://www.freeformatter.com/json-validator.html) gave this diagnosis: `The JSON input is NOT valid according to RFC 4627 (JSON specification). Unexpected character (}) at position 12514.`
Haven't easily found this position yet...

**Comment by wikfeldt** [comment]
is there maybe supposed to be a png image file where the caption is "The qubit frequency is: 4.009GHz"? This png is embedded in the notebook. If possible add the png file itself to the repo and link to it. I'm guessing that the error is because of the long string representing an image on line 276 in the json file

**Pull request closed without merging**
