### PR TITLE
Add intro to Helmi notebooks

### PR DESCRIPTION
**Pull request by JMuff22**
Hi, here are the Introduction to Helmi slides. Feedback and comments are welcome! I put these into their own folder under the notebooks directory. If there is a better place I can move them. 

Thanks!

### CODE REVIEW

**Comment by fomalhautn** [comment]
@JMuff22 please add this link https://docs.csc.fi/cloud/csc_notebooks/

**Comment by fomalhautn** [comment]
"star shaped topology"? Do you have a picture?

**Comment by fomalhautn** [comment]
Would you consider adding job monitoring for
```
job = execute(circuits_list, backend, shots=1000, optimization_level=0)
result = job.result()
plot_histogram(result.get_counts(), legend=['Circuit 1', 'Circuit 2'])
```
Something like:
```
from qiskit.tools.monitor import job_monitor

# Execute and monitor job
job = execute(circuits_list, backend, shots=1000, optimization_level=0)
print("Tracking execution of job:")
job_monitor(job)
```
```
# Get results
result = job.result()

# Plot histograms
plot_histogram(result.get_counts(), legend=['Circuit 1', 'Circuit 2'])
```

Screenshot 2023-10-02 at 14 13 57

**Comment by JMuff22** [comment]
> Would you consider adding job monitoring for
> 
> ```
> job = execute(circuits_list, backend, shots=1000, optimization_level=0)
> result = job.result()
> plot_histogram(result.get_counts(), legend=['Circuit 1', 'Circuit 2'])
> ```
> 
> Something like:
> 
> ```
> from qiskit.tools.monitor import job_monitor
> 
> # Execute and monitor job
> job = execute(circuits_list, backend, shots=1000, optimization_level=0)
> print("Tracking execution of job:")
> job_monitor(job)
> ```
> 
> ```
> # Get results
> result = job.result()
> 
> # Plot histograms
> plot_histogram(result.get_counts(), legend=['Circuit 1', 'Circuit 2'])
> ```
> 
> Screenshot 2023-10-02 at 14 13 57

Thanks for the feedback! I've added your suggestion to the notebook

**Review by wikfeldt — APPROVED** [review]
thanks Jake!

**Pull request merged**
