### PR TITLE
Add first version of ADAPT notebook

### PR DESCRIPTION
**Pull request by robertodr**

### CODE REVIEW

**Review by wikfeldt — APPROVED** [review]
thanks Roberto!

**Comment by wikfeldt** [comment]
ahh it's a draft. I'll hold my horses then

**Comment by robertodr** [comment]
Yes. I need to add some more text yet :)

**Comment by robertodr** [comment]
@wikfeldt I'll make some more changes to the ADAPT notebook, but they can be in follow-up PRs. This one can be merged at your leisure 😸

**Review by wikfeldt — APPROVED** [review]
excellent, thanks!

**Pull request merged**
